---
kind: List
apiVersion: v1
items:
- kind: Service
  apiVersion: v1
  metadata:
    namespace: default
    name: podevictionaid
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: podevictionaid
    labels:
      app: podevictionaid
  spec:
    publishNotReadyAddresses: true
    ports:
    - name: tcp-433
      port: 443
      targetPort: 8443
    selector:
      app: podevictionaid
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    namespace: default
    name: podevictionaid
    labels:
      app: podevictionaid
  spec:
    replicas: 1
    revisionHistoryLimit: 3
    progressDeadlineSeconds: 30

    selector:
      matchLabels:
        app: podevictionaid
    template:
      metadata:
        name: podevictionaid
        labels:
          app: podevictionaid
      spec:
        containers:
        - name: podevictionaid
          image: quay.io/klenkes74/podevictionaid:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
          volumeMounts:
          - mountPath: "/etc/ssl/private"
            name: ssl-certs
        volumes:
        - name: ssl-certs
          secret:
            secretName: podevictionaid
            defaultMode: 0700
- kind: MutatingWebhookConfiguration
  apiVersion: admissionregistration.k8s.io/v1beta1
  metadata:
    namespace: default
    name: podevictionaid
    labels:
      app: podevictionaid
  webhooks:
    - name: podevictionaid.default.svc
      clientConfig:
        service:
          name: podevictionaid
          namespace: default
          path: "/mutate"
      rules:
        - operations: ["CREATE"]
          apiGroups: [""]
          apiVersions: ["v1"]
          resources: ["pods"]
      namespaceSelector:
        matchLabels:
          podevictionaid: enabled
